# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
